---
name: Test
env:
  CONTAINER_IMAGE: deepakjotwani/sample2
on:
  push:
    branches: [master]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: echo qa_${GITHUB_SHA::7}
