---
name: Test

on:
  push:
    branches: [master, task/*, feature/*]

defaults:
  run:
    shell: bash
    working-directory: ./src

jobs:
  master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo master

  task-feature:
    if: github.ref == 'refs/heads/task*' || github.ref == 'refs/heads/feature*'
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo other
