---
name: Test

on:
  pull_request:
    branches:
      - "**"
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - name: echo-secret
        run: echo $USERNAME
    env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
