---
name: Test

on:
  pull_request:
    branches:
      - "**"
  workflow_run:
    workflows: ["Dependabot PR Workflow"]
    branches:
      - 'dependabot/**'
    types:
      - requested    
jobs:
  master:
    runs-on: ubuntu-latest
    if: ${{ (github.actor == 'dependabot[bot]' && (github.event.action == 'requested' || github.event.action == 'completed')) || (github.actor != 'dependabot[bot]') }}
    steps:
      - name: Checkout Code for dependabot PR
        if: ${{ github.actor == 'dependabot[bot]' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Check out Code
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/checkout@v2

      - name: echo-secret
        run: echo $USERNAME
    env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
