---
name: Test

on:
  push:
    branches: [master, task/*, feature/*]

jobs:
  master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: echo-branch-master
        run: echo "The selected branch is ${{ github.ref }}"
  
  task-feature:
    if: [[ ${{ github.ref }} =~ '/feature' ]] || [[ ${{ github.ref }} =~ '/task' ]]
    runs-on: ubuntu-latest
    steps:
      - name: echo-branch-test-feature
        run: echo "The selected branch is ${{ github.ref }}"
