---
name: Test

on:
  push:
    branches: [master, task/*, feature/*]

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - name: echo-branch-master
        run: echo "The selected branch is ${{ github.ref }}"

