---
name: Application CI Pipeline on Push
env:
  ARTIFACTORY_SCRATCH_BUCKET: eng-docker-scratch-local
  CONTAINER_SCRATCH_IMAGE: beyondtrust-$ARTIFACTORY_SCRATCH_BUCKET.jfrog.io/beyondtrust/cloud-privilege-broker/hostmachine
  ARTIFACTORY_PROD_BUCKET: eng-docker-prod-local
  CONTAINER_PROD_IMAGE: beyondtrust-$ARTIFACTORY_PROD_BUCKET.jfrog.io/beyondtrust/cloud-privilege-broker/hostmachine

on:
  push:
    branches: [master, task/*, feature/*]

defaults:
  run:
    shell: bash
    working-directory: ./src

jobs:
  master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo master

  task-feature:
    if: github.ref == 'refs/heads/task*' || github.ref == 'refs/heads/feature*'
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo other
