---
name: Application CI Pipeline on Push
env:
  CONTAINER_IMAGE: deepakjotwani/sample2

on:
  schedule:
    - cron: '0 12 * * *'
    - cron: '30 2 * * *'
jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: |
        Echo hello
